# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ,"dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies main proj
      run: dotnet restore ./lab78/proj/proj.csproj 
    - name: Build
      run: dotnet build --no-restore ./lab78/proj/proj.csproj
    - name: Install coverlet.msbuild
      continue-on-error: true
      run: dotnet add ./lab78/tests/tests.csproj package coverlet.msbuild  
    - name: Test 
      run: dotnet test ./lab78/lab78.sln /p:CollectCoverage=true
